### ISSUE TITLE
Compiling for 3.16 kernel.

### ISSUE THREAD

**Issue by andydvsn** [lwfinger/sa-btusb#1]
Any chance these drivers can be made to compile for the 3.16.x branch? I'm attempting to get an rtl8821cu based USB device (0bda:c820) and while the wifi can be made to work fine, there's no sign of life from the Bluetooth and none of the BT drivers I can find will compile under this older branch.

**Comment by lwfinger** [comment]
The short answer is probably not. The Bluetooth core has changed very dramatically. You might check with the backports project (https://backports.wiki.kernel.org/index.php/Main_Page) to see if they have backported BT as well as wifi.

**Comment by andydvsn** [comment]
Thanks, I've managed to build an rtk_btusb module from [this code](https://github.com/andydvsn/rtl8821cu_bt) and it seems to be working, though I'm still a little suspicious of it. Need to do some testing!
